.PHONY: clean All

All:
	@echo "----------Building project:[ DSSE_SAC - Debug ]----------"
	@cd "DSSE_SAC" && "$(MAKE)" -f  "DSSE_SAC.mk"
clean:
	@echo "----------Cleaning project:[ DSSE_SAC - Debug ]----------"
	@cd "DSSE_SAC" && "$(MAKE)" -f  "DSSE_SAC.mk" clean
